ALTER TABLE `GasStationHistory`
    MODIFY COLUMN `carStockId` BIGINT NOT NULL COMMENT '차량 재고 ID';

ALTER TABLE `CarTest`
    ADD COLUMN `updateMemberId` BIGINT NOT NULL COMMENT '수정인 ID';

ALTER TABLE `CarTest`
    ADD CONSTRAINT FK_CAR_TEST_UPDATE_MEMBER_ID FOREIGN KEY (updateMemberId) REFERENCES Member(id);